theme: jekyll-theme-cayman
title: DebitDirect.IO - RESTful direct debit services
description: DebitDirect provides modern restful integration API for enabling debit services like NETS LeverandørService
